### ISSUE TITLE
_readData bug, when 'value' happens to be missing for a row in the report

### ISSUE THREAD

**Issue by Felipe-90** [pitchmuc/adobe_analytics_api_2.0#16]
https://github.com/pitchmuc/adobe_analytics_api_2.0/blob/4c62414d41add59918d57a6a1b983c1044af10cb/aanalytics2/aanalytics2.py#L757

Hi pitchmuc. :)

I encountered another problem and I think, I have a fix for it.
When you pull your data from Adobe, but somehow you have a missing 'value', the code stops with a "KeyError: 'value'".
However, if you replace Line 757 with:
dict_data = {row.get('value'): row.get('data') for row in data_rows}
the code runs through and the resulting observations gets a 'None' as a key (can be changed by row.get('value', xyz) ).
You might still want to add some warning, or something if that happens.

On that topic see maybe:
https://stackoverflow.com/questions/11041405/why-dict-getkey-instead-of-dictkey

Best
Philipp

**Comment by pitchmuc** [comment]
Interesting ! 
I know the usage of dict.get() and it is probably used on other places through the code.

I wanted this piece to fail because we are constructing the dataframe. 
Doing it in the wrong way may create wrong reports and I prefer to fail (and debug) that to silently avoid the issue. 

I would be curious to know what is the reason for this fail because each row should have a value.
Did you find out why the "value" wasn't be found ? 

If possible a copy of the request statement would be great so I can integrate it in my tests request. 
Also how it looks in Workspace could probably help to see what are the value retrieved and why this is failing in my code.

**Comment by mrkobk** [comment]
hi,

have come across the very same issue. as AA UI doesnt return enough results I have tried to replicate in the Swagger UI, but was not able too = tried to set a limit of 5000 and a count of "value" keys returns 5000

for some dateRanges (usually just querying 24h) I get a key error "value" while other dateRanges work like a charm

is there any other way to resolve by a try/except or a NaN value that would not cause the run to fail + df to be generated properly.

thanks

**Comment by mrkobk** [comment]
@pitchmuc you able to please let me know if the above can be "fixed". appreciate your initial though was to let the function to fail on purpose, but would be great to understand, if there is a fix planned for the above KeyError in the near future or less so?

Thanks again
M

**Comment by pitchmuc** [comment]
Hey @mrkobk, 
I would like to have some data to see what is the data looking like. 
I never found that there was missing data in my tests and couldn't reproduce it so I wanted to make sure I am handling the case correctly. 
 Could you share somehow the response ?

**Comment by mrkobk** [comment]
thanks @pitchmuc ,
I'm afraid I cannot share the entire JSON response due to sensitive data, but I had added this screenshot: https://ibb.co/yVWB7WX in an earlier post. As the UI only returns 400 rows, I was not able to find the row with missing value to see how it looks, but the examples I got in the response that return a dict with no value key are always of very low hits (e.x. 1 visit or so). What is exactly causing some entries to have no value isnt something Im able to tell you Im afraid

**Comment by pitchmuc** [comment]
Thanks. 
I know it is not easy because it is client data, I appreciate the effort.
It seems to comfort my idea that this is a product issue from Oberon server. 
It would be worth to open a ticket to Client Care in order for them to explain them with Engineering. 

I will probably do the same fix that the one proposed. using the get() method on that dictionary but I need to flag it to the user. 
Probably putting "_missing value_"
What do you think ?

**Comment by mrkobk** [comment]
Thanks again! I'm happy to open a ticket there to see if there is anything they can do. For now my assumption was that it may be related to some tagging issues on my/client side. given that it is only affecting urls with 1 visit in my case I dont mind if the hit would not be included in the df, but I agree with your assessment that for completeness you could add the row with a "missing value" label. -->> actually thats what I was trying to do with the suggestion of replacing the comprehension with a for loop. this should allow to add the data row even with missing value key in the dict

**Comment by pitchmuc** [comment]
I'll publish the fix this week. 
Wondering if this is interpretated with the UI of Workspace as "Undefined"

**Comment by mrkobk** [comment]
appreciate it. many thanks
p.s.: kudos for the module. its awesome!

**Comment by pitchmuc** [comment]
I have uploaded a new version this morning (0.0.8) and it should solve that issue.
Could you try to upload the module by doing : 
`pip install aanalytics2 --upgrade` ? 
And tell me if that fixes the issue. 

Another question : Have you read the blog or watch the video for using the module ? (or none of that)

**Comment by mrkobk** [comment]
@pitchmuc many thanks. I have upgraded the module, but for some reason I still get the error. the error message suggest that you already using the get() method so frankly Im not sure why it is still throwing the error: https://prnt.sc/tucmoq

had checked your tutorials on youtube

**Comment by pitchmuc** [comment]
Perfect. I thought it didn't work at first. 
Thank you for providing feedback and thanks to your screenshot I was able to better understand what was happening. 
I needed you to check as well because at the moment, I am not able to reproduce it with my own data. 

I will close this Issue now.
