### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '...\\site-packages\\aanalytics2\\eventType_usageLogs.pickle'

### ISSUE THREAD

**Issue by loldenburg** [pitchmuc/adobe_analytics_api_2.0#47]
I tried to update to the newest version today, but cannot log in anymore. Could it be that the new better logging is related to this? Have no time to check this in detail at the moment, but rolling back for now to older version.

Traceback (most recent call last):
  File "C:\Users\Franz\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Franz\AppData\Local\Programs\Python\Python37\lib\importlib\resources.py", line 201, in path
    with open_binary(package, resource) as fp:
  File "C:\Users\Franz\AppData\Local\Programs\Python\Python37\lib\importlib\resources.py", line 91, in open_binary
    return reader.open_resource(resource)
  File "<frozen importlib._bootstrap_external>", line 929, in open_resource
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\gitrepos\\dim28-repo\\venv\\lib\\site-packages\\aanalytics2\\eventType_usageLogs.pickle'

**Comment by pitchmuc** [comment]
Hello,
yes, I noticed and it is already fixed.
please update to version 0.2.4.

For unknown reason, one file was not uploaded to pypi.
https://github.com/pitchmuc/adobe_analytics_api_2.0/blob/master/docs/releases.md

**Comment by loldenburg** [comment]
Thanks, but still does not work.

ERROR:root:Fatal Error in xxx.py: [Errno 2] No such file or directory: 'D:\\xxx\\venv2\\lib\\site-packages\\aanalytics2\\eventType_usageLogs.pickle'

**Comment by pitchmuc** [comment]
Interesting, your folder after installation should looks like this.
You may are missing the pickle files. 
![image](https://user-images.githubusercontent.com/32903178/107944204-18f9df00-6f8e-11eb-84e1-629f2859222a.png)

**Comment by pitchmuc** [comment]
Downloading the file from pypi, I can confirm that the file are in the wheel installation... 
![image](https://user-images.githubusercontent.com/32903178/107944469-7130e100-6f8e-11eb-8e86-754793d7de43.png)

Source : https://pypi.org/project/aanalytics2/#files

**Comment by loldenburg** [comment]
I install via git+https://github.com/pitchmuc/adobe_analytics_api_2.0.git@832ada23c9daaec358eb12267aaa096ad7c51925#egg=aanalytics2

**Comment by loldenburg** [comment]
are these pickle files a standard everywhere?

**Comment by pitchmuc** [comment]
They are files storing information to help with the use of the module. 
Basically, encapsulating the documentation references as dataframe. 
Example: 
![image](https://user-images.githubusercontent.com/32903178/107948569-55303e00-6f94-11eb-8619-65b35a75e04d.png)

or 
![image](https://user-images.githubusercontent.com/32903178/107948642-6a0cd180-6f94-11eb-858d-8b92a5e5b439.png)

**Comment by pitchmuc** [comment]
@loldenburg Can you try again ? 
I have made modification and added a MANIFEST.IN file to include the data. 
So it should work (you should have the file), if not I have put safeguard so it doesn't break anymore.

**Comment by loldenburg** [comment]
wonderful, that fixed it! THANKS!

**Comment by loldenburg** [comment]
Note however that the pickle files are still not downloaded (cannot see them in my aanalytics2 folders).

**Comment by pitchmuc** [comment]
OK... there are in the repo as well... 
It seems that you do not pick them for some reason. 

Is there a specific reason for not using `pip install aanalytics2 --upgrade` ?

**Comment by loldenburg** [comment]
In Google Cloud Repositories, you specify the modules in a requirements.txt file, so there is no pip.
But you can simply do
aanalytics2==0.2.4

I think the fact that I include your lib via Github is still from the time when your library did not support pip, it is also needed to get library versions or forks thereof which were not officially released (yet), e.g. to work around issues or test sth befor releasing it. Most importantly, it is probably one of those "never touch a running system" as every change I make usually breaks sth somewhere in the many scripts that already run on your wrapper (thanks!).

As long as the pip release version is avaible and stable, I think I could switch to pip for this library as well. 
Will try.

**Comment by loldenburg** [comment]
Local Test: Very interesting, this time the pickle files were indeed downloaded to the folders. Strange because that would mean there is no synchronicity between GIthub and pip modules in some cases. 

Now for the cloud test...

**Comment by pitchmuc** [comment]
I also tested your way of installing it and it downloaded the files as well. 
I am not sure why you couldn't with your pip command.

**Comment by loldenburg** [comment]
"I am not sure why you couldn't with your pip command."
I never used a pip command. I always did it via requirements.txt.

Cloud test also successful! :)

**Comment by pitchmuc** [comment]
Thanks for letting me know.
As a note: 
Normally for major fix (when there is something broken) I tend to do a quick release on pypi. 
It may be then the preferred default method. 
For other elements (adding new endpoints, etc..) I may be slower and then you may want to re-use the pip git+https...
